### ISSUE TITLE
Disabling the class-name rule

### ISSUE THREAD

**Issue by srividhyaramamoorthy** [bettermarks/bm-tslint-rules#17]
Unable to have the class name as `_ClassName` as we have the tslint rule enabled `class-name: true`.
This rule expects the class name should be in pascal case.

As we have decided to change `ComponentUnwrapped` to `_Component`, this rule can be disabled.

Note: Currently we are using inline tslint disable rule `tslint:disable-next-line:class-name` to create the class name in the format `_Component`.

**Comment by karfau** [comment]
This should then e adopted in the repository that uses the rules by changing the configuration fir this rule in the `tslint,json`.
I wouldn't generally remove the rule from this rule-set.
